//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Hang
    {
        public string soDH { get; set; }
        public string maKH { get; set; }
        public string taiKhoan { get; set; }
        public string hinhDD { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<System.DateTime> daKichHoat { get; set; }
        public Nullable<System.DateTime> ngayGH { get; set; }
        public string diaChiGH { get; set; }
        public string ghiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
