//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public string hinhDD { get; set; }
        public string ndTomTat { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public int maLoai { get; set; }
        public string noiDung { get; set; }
        public string dvt { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public Nullable<long> giaBan { get; set; }
        public Nullable<long> giamGia { get; set; }
        public string hangSanXuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
